jaxlims_database:
 name: rslims
 user: dba
 password: rsdba
 host: rslims.jax.org
 whereClause:

corepfs_database:
    #baseURL: https://jacksonlabstest.platformforscience.com/PROD-COPY-2/odata/
    baseURL: https://jacksonlabs.platformforscience.com/PROD/odata/
    experimentEndpointTemplate: KOMP_{exp}_EXPERIMENT?$filter=JAX_EXPERIMENT_STATUS eq 'Review Completed'&$expand=EXPERIMENT_SAMPLES($expand=ASSAY_DATA/pfs.KOMP_{exp}_ASSAY_DATA,ENTITY/pfs.MOUSE_SAMPLE_LOT($expand=SAMPLE/pfs.MOUSE_SAMPLE))
    mouseEndpoint: KOMP_REQUEST?$expand=REV_MOUSESAMPLELOT_KOMPREQUEST($expand=SAMPLE/pfs.MOUSE_SAMPLE($filter=Active eq true))
    experimentOnlyEndpointTemplate: KOMP_{}_EXPERIMENT?$filter=JAX_EXPERIMENT_STATUS eq 'Data Sent to DCC'&$count=true
    basicMouseInfoEndpoint: MOUSE_SAMPLE?$filter=Active eq true&$expand=MOUSE_SAMPLE_LOT($expand=SAMPLE)   
 
    username: svc-corePFS@jax.org
    password: hRbP&6K&(Qvw

jax_study:
    study: KOMP Phenotype
    eap: KOMP Phenotype
    lap: KOMP Aging

impc_pipeline:
    pipeline: JAX_001
    eap_pipeline: JAX_001
    ip_pipeline: JAXIP_001
    lap_pipeline: JAXLA_001

#BODY_WEIGHT
#AUDITORY_BRAINSTEM_RESPONSE
#BODY_COMPOSITION
#CLINICAL_BLOOD_CHEMISTRY
#ELECTROCARDIOGRAM
#ELECTRORETINOGRAPHY
#EYE_MORPHOLOGY
#FUNDUS_IMAGING
#GLUCOSE_TOLERANCE_TEST
#GRIP_STRENGTH
#HEART_WEIGHT
#HEMATOLOGY
#HOLEBOARD
#LIGHT_DARK_BOX
#OPEN_FIELD
#SHIRPA_DYSMORPHOLOGY
#STARTLE_PPI

impc_proc_codes:
    impc_code_list: STARTLE_PPI
    impc_all_code_list: OPEN_FIELD,HOLEBOARD,SHIRPA_DYSMORPHOLOGY,STARTLE_PPI,GRIP_STRENGTH,HEMATOLOGY,CLINICAL_BLOOD_CHEMISTRY,HEART_WEIGHT,BODY_COMPOSITION,GLUCOSE_TOLERANCE_TEST,ELECTROCARDIOGRAM,ELECTRORETINOGRAPHY,FUNDUS_IMAGING,EYE_MORPHOLOGY,AUDITORY_BRAINSTEM_RESPONSE,LIGHT_DARK_BOX
    
impc_proc_status_codes:
    
impc_param_status_codes:

filenames:
    dcc_xml_logfile_name: dcc_xml
    
directories:
    dest: C:\Users\michaelm\Source\Workspaes\Teams\Lab Informatics\JAXLIMS\Main\DccReporter\data\
    src: \\jax.org\jax\omero-drop\dropbox
    xml_log_path: .\log\

one-offs:
    #experimentEndpointTemplate: KOMP_{exp}_EXPERIMENT?$filter=JAX_EXPERIMENT_STATUS eq 'Review Completed'&$expand=EXPERIMENT_SAMPLES($expand=ASSAY_DATA/pfs.KOMP_{exp}_ASSAY_DATA,ENTITY/pfs.MOUSE_SAMPLE_LOT($expand=SAMPLE/pfs.MOUSE_SAMPLE))
    #experimentEndpointTemplate: KOMP_{exp}_EXPERIMENT?$filter= JAX_EXPERIMENT_STATUS eq 'Data Sent to DCC' and Name eq 'KSPE31'&$expand=EXPERIMENT_SAMPLES($expand=ASSAY_DATA/pfs.KOMP_{exp}_ASSAY_DATA,ENTITY/pfs.MOUSE_SAMPLE_LOT($expand=SAMPLE/pfs.MOUSE_SAMPLE))
    #experimentOnlyEndpointTemplate: KOMP_{}_EXPERIMENT?$filter=JAX_EXPERIMENT_STATUS eq 'Data Sent to DCC'&$count=true
    #experimentEndpointTemplate: KOMP_STARTLE_PPI_EXPERIMENT('KSPE3')?&$expand=EXPERIMENT_SAMPLES($expand=ASSAY_DATA/pfs.KOMP_STARTLE_PPI_ASSAY_DATA,ENTITY/pfs.MOUSE_SAMPLE_LOT($expand=SAMPLE/pfs.MOUSE_SAMPLE))
    #basicMouseInfoEndpoint: MOUSE_SAMPLE('{barcode}')IMENT

